### ISSUE TITLE
Clean up any auth-related TODOs (there are a few in my code that I had to leave until your parts were done)

### ISSUE THREAD

**Issue by kylekury** [kylekury/ideahub#21]

**Comment by mtakaki** [comment]
For whatever reason the idea resource is still reachable. I did some tests early today and it was working, not sure what disabled the authentication. I'll look this up when I wake up.

**Comment by kylekury** [comment]
The problem is that a commit of mine didn't go through. You edited com.ideahub.resources.IdeaResource, but the resource registered with the application is com.ideahub.resources.**idea**.IdeaResources.

I've moved things around and re-submitted, please test again.
